version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:4
    depends_on: [db]
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-app}?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    restart: "on-failure"

  api:
    build: .
    env_file: .env
    depends_on: [db, migrate]
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata: